import './globals.css'
import localFont from '@next/font/local'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const obibok = localFont({
	src: './fonts/convertet-obibok/Obibok-Inversed.woff2',
	variable: '--font-special',
});

const polisans = localFont({
	src: './fonts/PolySans-Neutral-web/PolySans-Neutral.woff2',
	variable: '--font-regular',
});

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${obibok.variable} ${polisans.variable} font-regular`}>{children}</body>
		</html>
	)
}
